services:
  mkdocs:
    image: squidfunk/mkdocs-material
    container_name: mkdocs
    networks:
      dns_network:
    volumes:
      - ${MKDOCS_VOLUME}:/docs
      - ${MKDOCS_SSH_VOLUME}:/root/.ssh:ro
      - $SSH_AUTH_SOCK:/ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    stdin_open: true
    tty: true

networks:
  dns_network:
    external: true
    driver: bridge


