services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    dns:
      - ${UNBOUND_DOCKER_IP}
      - ${PI_IP}
    environment:
      DOMAIN: ${DOMAIN}  # enter your domain
      SIGNUPS_ALLOWED: "false"                  # disable after creating your first account
      ADMIN_TOKEN: ${ARGON2_HASH}
    volumes:
      - ${VAULTWARDEN_VOLUME}:/data
    ports:
      - "8124:80/tcp"
